"""initial_m1_tables

Revision ID: 52abeae6c0ae
Revises: 
Create Date: 2026-07-27 22:03:18.922667
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52abeae6c0ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pairing_codes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pairing_codes_code'), 'pairing_codes', ['code'], unique=True)
    op.create_table('relationships',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('singleton_key', sa.String(length=1), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('singleton_key')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('relationship_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('apns_device_token', sa.String(length=256), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('persona_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('relationship_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('self_identity', sa.Text(), nullable=False),
    sa.Column('user_model', sa.Text(), nullable=False),
    sa.Column('relationship_definition', sa.Text(), nullable=False),
    sa.Column('core_traits', sa.Text(), nullable=False),
    sa.Column('agreements', sa.Text(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persona_versions')
    op.drop_table('devices')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_pairing_codes_code'), table_name='pairing_codes')
    op.drop_table('pairing_codes')
    # ### end Alembic commands ###
